---
- name: Ensure timesyncd is absent
  become: true
  ansible.builtin.package:
    name: systemd-timesyncd
    state: absent

- name: Ensure chrony is present
  become: true
  ansible.builtin.package:
    name: chrony
    state: present

- name: Ensure chrony sources.d support is configured
  become: true
  ansible.builtin.lineinfile:
    path: "{{ time_chrony_conf_path }}"
    regexp: "^\\s*sourcedir\\s+{{ chrony_sources_dropins_dir | regex_escape }}/?\\s*$"
    line: "sourcedir {{ chrony_sources_dropins_dir }}"
    state: present
    create: false
    backup: true
  when: chrony_sources_dropins_enabled

- name: Ensure chrony conf.d support is configured
  become: true
  ansible.builtin.lineinfile:
    path: "{{ time_chrony_conf_path }}"
    regexp: "^\\s*confdir\\s+{{ chrony_conf_dropin_dir | regex_escape }}/?\\s*$"
    line: "confdir {{ chrony_conf_dropin_dir }}"
    state: present
    create: false
    backup: true
  when: chrony_conf_dropin_enabled

- name: Install chronyd configuration
  become: true
  ansible.builtin.template:
    src: etc_chrony.conf.j2
    dest: "{{ time_chrony_conf_path }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart chronyd
  when: not chrony_conf_dropin_enabled

- name: Ensure chrony conf.d exists
  become: true
  ansible.builtin.file:
    path: "{{ chrony_conf_dropin_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: chrony_conf_dropin_enabled

- name: Ensure chrony sources.d exists
  become: true
  ansible.builtin.file:
    path: "{{ chrony_sources_dropins_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: chrony_sources_dropins_enabled

- name: Install chronyd conf.d drop-in
  become: true
  ansible.builtin.template:
    src: etc_chrony.conf.j2
    dest: "{{ chrony_conf_dropin_dir }}/{{ chrony_conf_dropin_file }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart chronyd
  when: chrony_conf_dropin_enabled

- name: Install chronyd source drop-ins
  become: true
  ansible.builtin.template:
    src: chrony_sources_file.conf.j2
    dest: "{{ chrony_sources_dropins_dir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ chrony_sources_dropins_files }}"
  notify:
    - Restart chronyd
  when: chrony_sources_dropins_enabled

- name: Enable chronyd
  become: true
  ansible.builtin.service:
    name: chronyd.service
    enabled: true
    state: started
