---
- name: Ensure timesyncd is absent
  become: true
  ansible.builtin.package:
    name: systemd-timesyncd
    state: absent

- name: Ensure chrony is present
  become: true
  ansible.builtin.package:
    name: chrony
    state: present

- name: Install chronyd configuration
  become: true
  ansible.builtin.template:
    src: etc_chrony.conf.j2
    dest: "{{ time_chrony_conf_path }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart chronyd
  when: not time_chrony_use_dropins

- name: Ensure chrony conf.d exists
  become: true
  ansible.builtin.file:
    path: "{{ ntp_sources_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: (ntp_sources_files | length > 0)

- name: Ensure chrony sources.d exists
  become: true
  ansible.builtin.file:
    path: /etc/chrony/sources.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: (ntp_sources_files | length > 0)

- name: Install chronyd conf.d drop-in
  become: true
  ansible.builtin.template:
    src: chrony_source_file.j2
    dest: "{{ ntp_sources_dir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ ntp_sources_files }}"
  notify:
    - Restart chronyd
  when: time_chrony_use_dropins

- name: Enable chronyd
  become: true
  ansible.builtin.service:
    name: chronyd.service
    enabled: true
    state: started
