---
- name: Load OS specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Override default time client variable
  set_fact:
    time_client: "{{ time_client_override }}"
  when: time_client_override is defined

- name: make sure unwanted packages are absent
  become: True
  package:
    name:
      - ntp
      - openntpd
    state: absent

- name: install tools
  become: True
  package:
    name: dbus
    state: present

- name: check for localtime symlink
  stat:
    path: /etc/localtime
  register: localtime

- name: remove /etc/localtime if it isn't a symlink
  become: True
  file:
    path: /etc/localtime
    state: absent
  when: localtime.stat.islnk is defined and localtime.stat.islnk == False

- name: set /etc/localtime symlink
  become: True
  file:
    path: /etc/localtime
    src: /usr/share/zoneinfo/{{ timezone_area }}/{{ timezone }}
    state: link
  when: (localtime.stat.islnk is defined and localtime.stat.islnk == False) or localtime.stat.exists == False

- include_tasks: "{{ time_client }}.yml"

- name: configure time settings with timedatectl
  become: True
  timezone:
      name: "{{ timezone_area }}/{{ timezone }}"
      hwclock: UTC

- meta: flush_handlers
