---
- name: make sure ntp is absent
  package:
    pkg: "{{item}}"
    state: absent
  with_items:
    - ntp
    - openntpd

- name: install tools
  package:
    name: "{{item}}"
    state: present
  with_items:
    - dbus

- name: check for localtime symlink
  stat:
    path: /etc/localtime
  register: localtime

- name: remove /etc/localtime if it isn't a symlink
  file: 
    path: /etc/localtime
    state: absent
  when: localtime.stat.islnk is defined and localtime.stat.islnk == False

- name: set /etc/localtime symlink
  file: 
    path: /etc/localtime
    src: /usr/share/zoneinfo/{{ timezone_area }}/{{ timezone }} 
    state: link
  when: (localtime.stat.islnk is defined and localtime.stat.islnk == False) or localtime.stat.exists == False

- name: install timesyncd configuration
  template: 
    src: etc_systemd_timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart timesyncd

- name: configure time settings with timedatectl
  timezone:
      name: "{{ timezone_area}}/{{timezone }}"
      hwclock: UTC

- meta: flush_handlers

