---
- name: restart timesyncd
  become: True
  service:
    name: systemd-timesyncd.service
    state: restarted

- name: restart chronyd
  become: True
  service:
    name: chronyd.service
    state: restarted
