---
- name: restart timesyncd
  service:
    name: systemd-timesyncd.service
    state: restarted

- name: restart chronyd
  service:
    name: chronyd.service
    state: restarted

- name: restart ntpd
  service:
    name: ntpd.service
    state: restarted
